### ISSUE TITLE
Dead Slack link

### ISSUE THREAD

**Issue by mrap** [realworldreact/reactathon2017#19]
"dedicated slack channel" link in apis.md is no longer active. Please update!

**Comment by dunphyben** [comment]
Works for me. Can you do a screenshot? Anyone else having issues?

**Comment by camdenb** [comment]
I'm also having this issue

**Comment by BerkeleyTrue** [comment]
You must be logged into the reactathon2017.slack.com channel for that link to work. Please follow the this link to join the slack if you haven't already. http://bit.ly/reactathon2017-slack

Happy Coding!
